### ISSUE TITLE
THIS GUY IS SPAMMING OMEGLE.COM!!!

### ISSUE THREAD

**Issue by OmegleSpammer** [SykieChen/BJUT-Gateway-Cracker#3]
HEY A$$HOLE! QUIT SPAMMING OMEGLE.COM WITH YOUR BS PAYPAL SCAM: 

http://nyan.im/1r

https://secure.yanvil.com/product/5628805

YOU'VE BEEN REPORTED TO NAMECHEAP, CLOUDFLARE, PAYPAL AND YOUR LOCAL POLICE DEPARTMENT FOR TRYING TO ENTICE CHILDREN INTO A SKYPE SEX SHOW! YOU WILL BE GOING TO JAIL!

**Comment by SykieChen** [comment]
What the hell are you talking about, sucker?
