### ISSUE TITLE
自动登录

### ISSUE THREAD

**Issue by N3verL4nd** [SykieChen/BJUT-Gateway-Cracker#6]
`@echo off  
mode con: cols=40 lines=15  
color 0a  
title  登录ing...  
rem 获得IP  
wget "https://lgn6.bjut.edu.cn/V6?https://lgn.bjut.edu.cn" --post-data="DDDDD=学号&upass=密码&v46s=0&v6ip=&f4serip=172.30.201.10&0MKKey=" -O ip.html  
ping 127.0.0.1 -n 2 >nul  
  
rem 登录 不显示结果--quiet  
set user="DDDDD=学号&upass=密码&0MKKey=Login&v6ip="  
@for /f "delims=" %%t in ('lua ip.lua') do set ip=%%t  
wget "https://lgn.bjut.edu.cn" --post-data=%user%%ip% -O ip.html  
ping www.baidu.com  
exit  `
其实发送POST请求就可以实现登录了

**Comment by SykieChen** [comment]
是的，这个问题已经解决啦。多谢。
