### ISSUE TITLE
error

### ISSUE THREAD

**Issue by N3verL4nd** [SykieChen/BJUT-Gateway-Cracker#7]
`N3verL4nd@DESKTOP-xiya MINGW64 /d/N3verL4nd/Desktop/BJUT-Gateway-Cracker-master
$ python crk.py
  File "crk.py", line 215
    print(count, " - Trying", u_name, "with password", u_pass, end='')
                                                                  ^
SyntaxError: invalid syntax
`

**Comment by SykieChen** [comment]
run with py3
